server1:
  build: .
  command: /usr/local/bin/consul agent -config-dir=/etc/consul.d/leader

server2:
  build: .
  links:
    - server1
  command: /usr/local/bin/consul agent -config-dir=/etc/consul.d/server

server3:
  build: .
  links:
    - server1
  command: /usr/local/bin/consul agent -config-dir=/etc/consul.d/server

web_ui:
  build: .
  links:
    - server1
  command: /usr/local/bin/consul agent -config-dir=/etc/consul.d/client -ui-dir=/var/www/
  ports:
    - "8500:8500"
